GET http://localhost:8000/api/cast-members/


###

GET http://localhost:8000/api/cast-members/7ca15e5a-d5ab-45e8-a61e-a3e68cf39ba4

###

POST http://localhost:8000/api/cast-members/
Content-Type: application/json

{
  "name": "Tarantino",
  "type": "DIRECTOR"
}

###

PUT http://localhost:8000/api/cast-members/b1ab26b9-3e93-4ea8-b39c-14e6cdf6af59/
Content-Type: application/json

{
  "name": "Quentin Tarantino",
  "type": "DIRECTOR"
}

###

DELETE http://localhost:8000/api/cast-members/b1ab26b9-3e93-4ea8-b39c-14e6cdf6af59/