@access_token = {{session.response.body.access_token}}

###

# @name session
POST http://localhost:8080/realms/codeflix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=codeflix-frontend&grant_type=password&username=admin@admin.com&password=admin

###

GET http://localhost:8000/api/categories
Authorization: Bearer {{access_token}}


###

GET http://localhost:8000/api/categories/ad25cb7b-7af1-43ff-b329-407364423fb3

###

POST http://localhost:8000/api/categories/
Content-Type: application/json

{
  "name": "Sports",
  "description": "Best movie"
}

###

PUT http://localhost:8000/api/categories/ad25cb7b-7af1-43ff-b329-407364423fb3/
Content-Type: application/json

{
  "name": "Movie",
  "description": "Category 2 description",
  "is_active": true
}

###

DELETE http://localhost:8000/api/categories/ad25cb7b-7af1-43ff-b329-407364423fb3/