GET http://localhost:8000/api/categories?order_by=description


###

GET http://localhost:8000/api/categories/a78028b2-2b8b-468f-a06e-db717bf40d67

###

POST http://localhost:8000/api/categories/
Content-Type: application/json

{
  "name": "Crime",
  "description": "Best movie"
}

###

PUT http://localhost:8000/api/categories/a78028b2-2b8b-468f-a06e-db717bf40d67/
Content-Type: application/json

{
  "name": "Movie",
  "description": "Category 2 description",
  "is_active": true
}