# @name create_video
POST http://localhost:8000/api/videos/
Content-Type: application/json

{
    "title": "Interestellar 3",
    "description": "Description 1",
    "launch_year": 2020,
    "opened": false,
    "published": true,
    "rating": "ER",
    "duration": 1,
    "categories": [
        "de08c424-045c-4054-a345-66f23ccface6"
    ],
    "genres": [
        "68d8cb3a-1be7-454f-983f-dd7a3182ee6f"
    ],
    "cast_members": [
        "681eabdf-ed3b-4af3-8365-79971f1bb494"
    ]
}

###

# @name list_videos
GET http://localhost:8000/api/videos?order_by=title&current_page=2

###

# @name get_video
GET http://localhost:8000/api/videos/eaacb7df-086d-4a09-987d-3253d55ad5fb


###

# @name delete_video
DELETE http://localhost:8000/api/videos/eaacb7df-086d-4a09-987d-3253d55ad5fb/


###

# @name upload_video
PATCH http://localhost:8000/api/videos/1e3e4bb6-91b4-4723-a1ff-eecfbf7e8f55/
Content-Type: multipart/form-data

video_file=@C:\\tmp\\codeflix-storage\\videos\\121\\video.mp4;type=video/mp4
