# @name create_video
POST http://localhost:8000/api/videos/
Content-Type: application/json

{
    "title": "Interestellar 3",
    "description": "Description 1",
    "launch_year": 2020,
    "opened": false,
    "published": true,
    "rating": "ER",
    "duration": 1,
    "categories": [
        "91975f9a-f4a0-4c7d-b23f-cd10e3fd501c"
    ],
    "genres": [
        "c65d76ae-bd86-4861-9554-8deedf2fbb65"
    ],
    "cast_members": [
        "1117d3af-a01e-4d7f-b95a-af4cf8afb0cb"
    ]
}

###

# @name list_videos
GET http://localhost:8000/api/videos?order_by=title&current_page=2

###

# @name get_video
GET http://localhost:8000/api/videos/eaacb7df-086d-4a09-987d-3253d55ad5fb


###

# @name delete_video
DELETE http://localhost:8000/api/videos/eaacb7df-086d-4a09-987d-3253d55ad5fb/