# Generated by Django 5.1.2 on 2024-11-09 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("DIRECTOR", "DIRECTOR"), ("ACTOR", "ACTOR")],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "cast_member",
            },
        ),
    ]
