# Generated by Django 5.1.2 on 2024-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="opened",
            field=models.BooleanField(default=False),
        ),
    ]
